/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_teoriaconjuntos;

/**
 *
 * @author csegura
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    Operaciones Datos = new Operaciones();
    int Contador=1;
    boolean ConjuntoA= false;
    boolean ConjuntoB = false;
    
    public MenuPrincipal() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        Txt_Con_Res.setEnabled(false);
        Btn_Union.setEnabled(false);
        Btn_Interseccion.setEnabled(false);
        Btn_Diferencia.setEnabled(false);
        Btn_DiferenciaSi.setEnabled(false);
        Btn_Limpiar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_Con_A = new javax.swing.JTextField();
        Txt_Con_B = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_Con_Res = new javax.swing.JTextField();
        Btn_Union = new javax.swing.JButton();
        Btn_DatosA = new javax.swing.JButton();
        Btn_DatosB = new javax.swing.JButton();
        Lbl_Res = new javax.swing.JLabel();
        lbl_DatosA = new javax.swing.JLabel();
        lbl_DatosB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_Interseccion = new javax.swing.JButton();
        Btn_Diferencia = new javax.swing.JButton();
        Btn_DiferenciaSi = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Conjunto A");

        jLabel2.setText("Conjunto B");

        jLabel3.setText("Resultado");

        Txt_Con_Res.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt_Con_Res.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Btn_Union.setText("UNION");
        Btn_Union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UnionActionPerformed(evt);
            }
        });

        Btn_DatosA.setText("Ingresar");
        Btn_DatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DatosAActionPerformed(evt);
            }
        });

        Btn_DatosB.setText("Ingresar");
        Btn_DatosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DatosBActionPerformed(evt);
            }
        });

        Lbl_Res.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Lbl_Res.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Res.setText("RESULTADO");

        lbl_DatosA.setForeground(new java.awt.Color(255, 51, 51));

        lbl_DatosB.setForeground(new java.awt.Color(255, 51, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Operaciones de Conjuntos");

        Btn_Interseccion.setText("INTERSECCION");
        Btn_Interseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InterseccionActionPerformed(evt);
            }
        });

        Btn_Diferencia.setText("DIFERENCIA");
        Btn_Diferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DiferenciaActionPerformed(evt);
            }
        });

        Btn_DiferenciaSi.setText("DIFERENCIA SIMETRICA");
        Btn_DiferenciaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DiferenciaSiActionPerformed(evt);
            }
        });

        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        jButton1.setText("Integrantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_DiferenciaSi)
                        .addGap(288, 288, 288)
                        .addComponent(Btn_Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(Txt_Con_A, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Btn_DatosA))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Con_B, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_DatosB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_DatosB, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Btn_Diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Union, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Lbl_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Btn_Interseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Txt_Con_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jButton1)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_Con_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_DatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_Con_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DatosB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lbl_DatosB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Union)
                    .addComponent(Lbl_Res))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Btn_Interseccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Diferencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Txt_Con_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_DiferenciaSi)
                    .addComponent(Btn_Limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_UnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UnionActionPerformed
        // TODO add your handling code here:
        Txt_Con_Res.setText("{" +Datos.Union()+"}"); 
        Lbl_Res.setText("R = A"+ " U " +"B");
        
    }//GEN-LAST:event_Btn_UnionActionPerformed

    private void Btn_DatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DatosAActionPerformed

        
        String linea = Txt_Con_A.getText();
        String[] textElements = linea.split("[;,]");
        
        Datos.ConjuntoCa(textElements.length);
        
        for(String s:textElements) 
        {
            Datos.Ca(s,Contador-1);
            Contador++;
            
            if (Contador > Datos.Long_ConA())
            {
                String ConjuntoA="";
                for(int i = 1; i<= Datos.Long_ConA(); i++)
                {
                    //Txt_Con_A.setText(Txt_Con_A.getText() + Muestra.Con_a(i-1)+";");
                    ConjuntoA = ConjuntoA + Datos.Con_a(i-1)+";";
                    Txt_Con_A.setText(ConjuntoA);
                }
                Txt_Con_A.setText("{"+Txt_Con_A.getText()+"}");
                Contador=1;
                //Btn_DatosA.setEnabled(false);
            }
            else
            {
                lbl_DatosA.setText("Conjunto A de:" + Datos.Long_ConA()+ " Elementos");
            }
        }
        Txt_Con_A.setEnabled(false);
        Txt_Con_A.setOpaque(true);
        Btn_DatosA.setEnabled(false);
        Txt_Con_B.requestFocus();
        ConjuntoA=true;
        
        if(ConjuntoA && ConjuntoB)
        {
            Btn_Union.setEnabled(true);
            Btn_Interseccion.setEnabled(true);
            Btn_Diferencia.setEnabled(true);
            Btn_DiferenciaSi.setEnabled(true);
            Btn_Limpiar.setEnabled(true);
        }

        
        
    }//GEN-LAST:event_Btn_DatosAActionPerformed

    private void Btn_DatosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DatosBActionPerformed
        //Obtengo los datos ingresados
        String linea = Txt_Con_B.getText();
        //Separa cada elemento, diferenciandolos por los separadores ingresados
        String[] textElements = linea.split("[;,]");
        
        //Obtengo el tamaño del arreglo para saber el tamaño de elementos.
        Datos.ConjuntoCb(textElements.length);
        
        //Leer el arreglo para ingresar los elementos del conjunto.
        for(String s:textElements) 
        {
            Datos.Cb(s,Contador-1);
            Contador++;
            
            if (Contador > Datos.Long_ConB())
            {
                String ConjuntoB="";
                for(int i = 1; i<= Datos.Long_ConB(); i++)
                {
                    ConjuntoB = ConjuntoB + Datos.Con_b(i-1)+";";
                    Txt_Con_B.setText(ConjuntoB);
                }
                Txt_Con_B.setText("{"+Txt_Con_B.getText()+"}");
                Contador=1;
            }
            else
            {
                lbl_DatosB.setText("Conjunto B de:" + Datos.Long_ConB()+ " Elementos");
            }
        }
        Txt_Con_B.setEnabled(false);
        Txt_Con_B.setOpaque(true);
        Btn_DatosB.setEnabled(false);
        ConjuntoB=true;
        
        if(ConjuntoA && ConjuntoB)
        {
            Btn_Union.setEnabled(true);
            Btn_Interseccion.setEnabled(true);
            Btn_Diferencia.setEnabled(true);
            Btn_DiferenciaSi.setEnabled(true);
            Btn_Limpiar.setEnabled(true);
        }

        
    }//GEN-LAST:event_Btn_DatosBActionPerformed

    private void Btn_InterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InterseccionActionPerformed
        
        Txt_Con_Res.setText("{" +Datos.Interseccion()+"}"); 
        Lbl_Res.setText("R = A ∩ B");
  
    }//GEN-LAST:event_Btn_InterseccionActionPerformed

    private void Btn_DiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DiferenciaActionPerformed
        Txt_Con_Res.setText("{" +Datos.Diferencia()+"}"); 
        Lbl_Res.setText("R = A - B");
    }//GEN-LAST:event_Btn_DiferenciaActionPerformed

    private void Btn_DiferenciaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DiferenciaSiActionPerformed
         Txt_Con_Res.setText("{" +Datos.DiferenciaSimetrica()+"}"); 
        Lbl_Res.setText("R = A ∆ B");
    }//GEN-LAST:event_Btn_DiferenciaSiActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
            Btn_Union.setEnabled(false);
            Btn_Interseccion.setEnabled(false);
            Btn_Diferencia.setEnabled(false);
            Btn_DiferenciaSi.setEnabled(false);
            Btn_Limpiar.setEnabled(false);
            Txt_Con_A.setEnabled(true);
            Btn_DatosA.setEnabled(true);
            Txt_Con_A.setText("");
            Txt_Con_B.setText("");
            Txt_Con_Res.setText("");
            lbl_DatosA.setText("");
            lbl_DatosB.setText("");
            
            Txt_Con_B.setEnabled(true);
            Btn_DatosB.setEnabled(true);
        
        
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Integrantes ventana = new Integrantes();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_DatosA;
    private javax.swing.JButton Btn_DatosB;
    private javax.swing.JButton Btn_Diferencia;
    private javax.swing.JButton Btn_DiferenciaSi;
    private javax.swing.JButton Btn_Interseccion;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Union;
    private javax.swing.JLabel Lbl_Res;
    private javax.swing.JTextField Txt_Con_A;
    private javax.swing.JTextField Txt_Con_B;
    private javax.swing.JTextField Txt_Con_Res;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_DatosA;
    private javax.swing.JLabel lbl_DatosB;
    // End of variables declaration//GEN-END:variables
}
